name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build standard
      run: cargo build --target aarch64-unknown-linux-gnu --release
    - name: Build no config
      run: cargo build --target aarch64-unknown-linux-gnu --release --no-default-features
