name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Configure
      run: |
        sudo apt-get update
        rustup target add aarch64-unknown-linux-gnu
        sudo apt-get install gcc-aarch64-linux-gnu
    - name: Build standard
      run: cargo build --target aarch64-unknown-linux-gnu --release
    - uses: actions/upload-artifact@v3
      with:
        name: package
        path: |
          target/aarch64-unknown-linux-gnu/release/argon_fan_controller
          argon_fan_controller.service
          argon_fan_controller_cfg.yml
          deploy.sh
